// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uKzMYqiY71LewgafZ2KgTy
// Component: zS3XS1-A4p3bA
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_new_figma_test.module.css"; // plasmic-import: uKzMYqiY71LewgafZ2KgTy/projectcss
import * as sty from "./PlasmicRwBanner.module.css"; // plasmic-import: zS3XS1-A4p3bA/css

export type PlasmicRwBanner__VariantMembers = {};

export type PlasmicRwBanner__VariantsArgs = {};
type VariantPropType = keyof PlasmicRwBanner__VariantsArgs;
export const PlasmicRwBanner__VariantProps = new Array<VariantPropType>();

export type PlasmicRwBanner__ArgsType = {};
type ArgPropType = keyof PlasmicRwBanner__ArgsType;
export const PlasmicRwBanner__ArgProps = new Array<ArgPropType>();

export type PlasmicRwBanner__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultRwBannerProps {
  className?: string;
}

function PlasmicRwBanner__RenderFunc(props: {
  variants: PlasmicRwBanner__VariantsArgs;
  args: PlasmicRwBanner__ArgsType;
  overrides: PlasmicRwBanner__OverridesType;
  dataFetches?: PlasmicRwBanner__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div className={classNames(defaultcss.all, sty.freeBox__vqrGd)}>
        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox___5SCt
          )}
        >
          {"Most popular"}
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRwBanner__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicRwBanner__VariantsArgs;
    args?: PlasmicRwBanner__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicRwBanner__Fetches;
  } & Omit<PlasmicRwBanner__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicRwBanner__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRwBanner__ArgProps,
      internalVariantPropNames: PlasmicRwBanner__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicRwBanner__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRwBanner";
  } else {
    func.displayName = `PlasmicRwBanner.${nodeName}`;
  }
  return func;
}

export const PlasmicRwBanner = Object.assign(
  // Top-level PlasmicRwBanner renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicRwBanner
    internalVariantProps: PlasmicRwBanner__VariantProps,
    internalArgProps: PlasmicRwBanner__ArgProps
  }
);

export default PlasmicRwBanner;
/* prettier-ignore-end */
